1) List slicing: Run the cell below 

In [1]:
list_nums = [3,6,9,13,47,101,102,104,105,200,301]

a) print the whole list

In [2]:
print(list_nums)

[3, 6, 9, 13, 47, 101, 102, 104, 105, 200, 301]


b) print all numbers from 13 to 200

In [3]:
print(list_nums[3:10])

[13, 47, 101, 102, 104, 105, 200]


c) print the list in reverse

In [4]:
print(list_nums[::-1])

[301, 200, 105, 104, 102, 101, 47, 13, 9, 6, 3]


d) extract numbers 3 to 104, missing out every other number (e.g. 3, 9, 47, 102). Save this in a new variable and then print it

In [5]:
a = [list_nums[0], list_nums[7]]
print(a)

[3, 104]


Run the cell below

In [6]:
sentence = "Hello, I like christmas trees!"

e) print just "christmas trees" from the variable 'sentence'

In [7]:
print(sentence[14:])

christmas trees!


f) print the full sentence but in reverse

In [8]:
print(sentence[::-1])

!seert samtsirhc ekil I ,olleH


Bonus: Below is a matrix. In a previous lecture we touched on lists within lists.
This is a very important concept in Machine Learning. Below is a matrix (lists, within lists, within lists). 
Here is a list within a list: 

In [9]:
#Run this cell
list_list = [[1,2,3],[4,5,6]]

To extract either of the lists you can just use list_list[0] or list_list[1]. But to extract a number from a list, e.g. 
the number 4 you would first extract the second list with list_list[1] and then immediately after [0], so it looks like this: 
list_list[1][0]. Try it below (run the cell above first)

In [10]:
list_list[1][0]

4

Try it yourself now with a matrix (hint to extract just a number you will need to do matrix[][][]!)

Run the cell below:

In [11]:
matrix = [[[1,5,2,0.5],[0.2,0.7,19,299]],[[0.11,13,15.7,19,20],[1,0.1,0.01,0.2,20,23,1000]]]

g) print out the first two list (keep in mind they are within the same list - [[1,5,2,0.5],[0.2,0.7,19,299]])

In [13]:
matrix[0]

[[1, 5, 2, 0.5], [0.2, 0.7, 19, 299]]

h) print out just the first list

In [14]:
matrix[0][0]

[1, 5, 2, 0.5]

i) print out the number 19 1000 from matrix

In [19]:
print(matrix[0][1][2])
print(matrix[1][1][6])

19
1000


2) Sets and tuples

a) Turn the list below into a set (make sure to run the cell to create the variable):

In [21]:
List_names = ["Jim","Jackie","Harry","Jim","Hywel","Jackie","Hywel"]
set(List_names)

{'Harry', 'Hywel', 'Jackie', 'Jim'}

b) What is one of the main purposes of sets?

In [ ]:
To reduce redudances

c) How is a tuple different to a list?

In [ ]:
a tuple is immutable as opposed to a list

3) Dictionaries

a) Create a dictionary below with five different key-value pairs. Hint {key:value, key2:value}

In [22]:
bank_accounts = {"Muamer Rastic": 0, "Elvedin Radonjica": 1200, "Nehad Rastic": 450, "a" : 440, "b" : 5212}

b) Add a new key-value pair to your dictionary

In [23]:
bank_accounts["c"] = "Erko Rastic"

c) Print just one key-value pair from the dictionary

In [24]:
print(bank_accounts["c"])

Erko Rastic


d) change the values of our of your keys

In [26]:
bank_accounts["b"] = 120

In [27]:
print(bank_accounts)

{'Muamer Rastic': 0, 'Elvedin Radonjica': 1200, 'Nehad Rastic': 450, 'a': 440, 'b': 120, 'c': 'Erko Rastic'}


In [29]:
Da == da


NameError: name 'Da' is not defined